# -*- coding: utf-8 -*-
"""Bot_Telegram.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18PhnQXNGxdaZv416jA-kxgiDl-TN21hX
"""

token='8822068083:AAHvt2b8i2yCs3TjuTaYCdGj_5JIh2n8TZw'

pip install pyTelegramBotAPI

pip install git+https://github.com/openai/whisper.git

pip install ultralytics

import telebot
import whisper
from ultralytics import YOLO
model=whisper.load_model('base')
yolo_model=YOLO('yolov8n.pt')

bot=telebot.TeleBot(token)

@bot.message_handler(content_types=['photo'])
def responder_imagem(mensagem):
  bot.reply_to(mensagem, "Você enviou uma imagem! Processando...")
  #print(mensagem)
  file_id = mensagem.photo[-1].file_id

  #Pegar informações (como file path)
  file_info = bot.get_file(file_id)

  #Fazer download do conteúdo do arquivo
  downloaded_file = bot.download_file(file_info.file_path)

  #Salvar arquivo localmente
  filename = 'downloaded_photo.jpeg'
  with open(filename, 'wb') as new_file:
    new_file.write(downloaded_file)
  #bot.reply_to(mensagem, "Photo saved successfully!")

  #Usa o modelo YOLO sobre a imagem original.
  results=yolo_model(filename)
  for result in results:
    result.save('result.jpeg')

  # Pega o ID do usuário que enviou a mensagem
    chat_id = mensagem.chat.id

  # Abre a foto e a armazena como um objeto.
  imagem = open("result.jpeg", "rb")

  # Envia a foto
  bot.send_photo(chat_id, imagem, caption="Detecção de objetos")


@bot.message_handler(content_types=['voice','audio'])
def responder_audio(mensagem):
  bot.reply_to(mensagem, "Você enviou um áudio! Processando...")
  #print(mensagem)
  #Determina se é um arquivo de audio ou mensagem de voz para conseguir file_id
  file_id = mensagem.audio.file_id if mensagem.content_type == 'audio' else mensagem.voice.file_id

  #Pegar informações (como file path)
  file_info = bot.get_file(file_id)

  #Fazer download do conteúdo do arquivo
  downloaded_file = bot.download_file(file_info.file_path)

  #Salvar arquivo localmente
  filename = 'downloaded_audio.mp3'
  with open(filename, 'wb') as new_file:
    new_file.write(downloaded_file)
  #bot.reply_to(mensagem, "Audio saved successfully!")

  #Carrega e prepara 30 segundos de áudio
  audio = whisper.load_audio(filename)
  audio = whisper.pad_or_trim(audio)

  # Gera o espetrograma log-Mel
  mel = whisper.log_mel_spectrogram(audio).to(model.device)

  #Detecta a lingua falada
  _, probs = model.detect_language(mel)

  #Identifica a lingua com maior probabilidade
  detected_lang = max(probs, key=probs.get)
  bot.reply_to(mensagem, f"Língua Detectada: {detected_lang}")

  #Converte o áudio em texto
  result=model.transcribe(filename)
  bot.reply_to(mensagem, result['text'])

@bot.message_handler(content_types=['text'])
def responder(mensagem):
  texto = 'Envie uma imagem ou um áudio para ser processado.'
  bot.reply_to(mensagem, texto)

@bot.message_handler(content_types=['document', 'sticker', 'video', 'video_note', 'animation'])
def responder_audio(mensagem):
  bot.reply_to(mensagem, "Formato de arquivo não suportado")

bot.polling()