# -*- coding: utf-8 -*-
"""botdotelegram.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XzCChH09pbG18tuf4bhd1JBr8aETzjjY

Grupo 3: Isadora, Kauã e Yuri
"""

from datetime import datetime
from telegram.ext import Application, ContextTypes, MessageHandler, filters
from telegram import Update

def log(msg: str):
  """Registra uma nova entrada no arquivo de log. Agrs: msg (str): Texto que será armazenado no log, acompanhado da data e do horário do registro."""
    with open("log.txt", "a") as f:
        f.write(f"[{datetime.now()}]" + msg + "\n")

class BotTelegram:
  """Classe responsável pela configuração e gerenciamento do bot do Telegram. Inicializa a aplicação do bot, protege o token de acesso por meio de encapsulamento e encaminha as mídias recebidas para o processamento adequado.
Atributos: application (Application): Instância da aplicação utilizada para executar e gerenciar o bot"""
  def __init__ (self, token: str):
    """Inicializa o bot e configura o interceptador de mensagens. Args: token (str): Token privado gerado pelo BotFather."""
    self.__token = token
    self.application = Application.builder().token(self.__token).build()
    self.application.add_handler(MessageHandler(filters.ALL & ~filters.COMMAND, self.retorno))
  def iniciando_bot (self):
    """Ativa o recebimento contínuo de mensagens (modo polling)."""
    log("Bot ativado")
    print("Bot em funcionamento")
    app.run_polling()
  async def retorno (self, update, context):
    """Encaminha o arquivo recebido para o processamento de acordo com seu tipo."""
     if update.message.photo:
        log("Arquivo de imagem recebido")
        await self.processar_imagem(update, context)
    elif update.message.voice:
        log("Arquivo de áudio recebido")
        await self.processar_audio(update, context)
    elif update.message.text:
        await update.message.reply_text("Seu texto foi recebido, no entanto só retorno informações de arquivos de áudio e imagem")
    else:
        await update.message.reply_text("Não fui programado para processar esse tipo de arquivo, envie uma imagem ou um áudio")
  async def processar_imagem(self, update,context):
    """Define a interface abstrata para o processamento de imagens com YOLO. Este método deve ser obrigatoriamente implementado pela classe derivada `BotImagem`."""
      await update.message.reply_text("Processamento de imagem não implementado nesta classe.")
  async def processar_audio(self, update, context):
     """Define a interface abstrata para transcrição de áudio (Speech-to-Text). Este método deve ser obrigatoriamente implementado pela classe derivada `BotAudio`."""
      await update.message.reply_text("Processamento de áudio não implementado nesta classe.")

token = "8334055646:AAF4ZQZiqj6_I2JIewfAksLJOtWXGet-wys"
bot = BotTelegram(token)
bot.iniciar()