# -*- coding: utf-8 -*-
"""botdotelegram.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XzCChH09pbG18tuf4bhd1JBr8aETzjjY

Grupo 3: Isadora, Kauã e Yuri
"""

# criação do bot

from telegram import Updates
from telegram.ext import (Application, CommandHandler, MessageHandler,ContextType, filters)

class BotTelegram:
  def __init__ (self, token):
    self.__token = token
   def iniciando_bot (self):
    builder = Application.builder()
    builder.token(self.__token)
    app = builder.build()
    app.add_handler(MessageHandler(filters.ALL,self.retorno))
    app.run_polling()
  async def retorno (self, update, context):
    if uptade.message.photo:
      await update.message.reply_text("Imagem recebida, iremos analisar o conteúdo")
    elif update.message.voice:
      await update.message.reply_text("Audio recebido, iremos analisar o conteúdo")
    elif update.message.text:
      await update.message.reply_text("Texto recebido, iremos analisar o conteúdo")
    else:
      await update.message.reply_text("Arquivo recebido, porém não fui programado para processar esse tipo de arquivo. Envie arquivos de fotos ou aúdios")

#main

from botdotelegram import BotTelegram
token = "colocar o token aqui quando criar o bot no telegram"
bot = BotTelegram(TOKEN)
bot.iniciando_bot()